package com.dataguise.webservices.beans;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "ParseException", targetNamespace = "http://webservices.dataguise.com/")
public class ParseException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private ParseException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public ParseException_Exception(String message, ParseException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public ParseException_Exception(String message, ParseException faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.dataguise.webservices.beans.ParseException
	 */
	public ParseException getFaultInfo() {
		return faultInfo;
	}

}
