
package com.dataguise.webservices.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PrototypeServicePortType", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PrototypeServicePortType {


    /**
     * 
     * @param nMapScan
     * @return
     *     returns com.dataguise.NMapTaskIdAckElement
     */
    @WebMethod(action = "startDatabaseFind")
    @WebResult(name = "NMapTaskIdAckElement", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", partName = "NMap-TaskIdAck")
    public NMapTaskIdAckElement startDatabaseFind(
        @WebParam(name = "AbstractNMapScan", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", partName = "NMap-Scan")
        NMapScan nMapScan);

    /**
     * 
     * @param nMapTaskIdScan
     * @return
     *     returns com.dataguise.NMapStatus
     */
    @WebMethod(action = "getDatabaseFindStatus")
    @WebResult(name = "NMapStatus", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", partName = "NMap-Status")
    public NMapStatus getDatabaseFindStatus(
        @WebParam(name = "NMapTaskIdScanElement", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", partName = "NMap-TaskIdScan")
        NMapTaskIdScanElement nMapTaskIdScan);

    /**
     * 
     * @param nMapTaskIdResults
     * @return
     *     returns com.dataguise.NMapOutputArray
     */
    @WebMethod(action = "getDatabaseFindResults")
    @WebResult(name = "NMapOutputArray", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", partName = "NMap-OutputArray")
    public NMapOutputArray getDatabaseFindResults(
        @WebParam(name = "NMapTaskIdResultsElement", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", partName = "NMap-TaskIdResults")
        NMapTaskIdResultsElement nMapTaskIdResults);

}
