
package com.dataguise.webservices.beans;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PrototypeService", targetNamespace = "http://ws.dataguise.com/PrototypeServiceTest", wsdlLocation = "file:/C:/DataGuise/src/Enterprise/dgAgent/Discover/Prototype/DgDiscoverPrototypeServlet/WSDL/ControllerUIPortType.wsdl")
public class PrototypeService
    extends Service
{

    private final static URL PROTOTYPESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.dataguise.webservices.beans.PrototypeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.dataguise.webservices.beans.PrototypeService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/DataGuise/src/Enterprise/dgAgent/Discover/Prototype/DgDiscoverPrototypeServlet/WSDL/ControllerUIPortType.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/DataGuise/src/Enterprise/dgAgent/Discover/Prototype/DgDiscoverPrototypeServlet/WSDL/ControllerUIPortType.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROTOTYPESERVICE_WSDL_LOCATION = url;
    }

    public PrototypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrototypeService() {
        super(PROTOTYPESERVICE_WSDL_LOCATION, new QName("http://ws.dataguise.com/PrototypeServiceTest", "PrototypeService"));
    }

    /**
     * 
     * @return
     *     returns PrototypeServicePortType
     */
    @WebEndpoint(name = "ControllerUIPortType")
    public PrototypeServicePortType getControllerUIPortType() {
        return super.getPort(new QName("http://ws.dataguise.com/PrototypeServiceTest", "ControllerUIPortType"), PrototypeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrototypeServicePortType
     */
//    @WebEndpoint(name = "ControllerUIPortType")
//    public PrototypeServicePortType getControllerUIPortType(WebServiceFeature... features) {
//        return super.getPort(new QName("http://ws.dataguise.com/PrototypeServiceTest", "ControllerUIPortType"), PrototypeServicePortType.class, features);
//    }

}
