package com.dataguise.webservices.beans.masker;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.dataguise.webservices.beans.DgColumnDetails;
import com.dataguise.webservices.beans.DgColumnInfo;
import com.dataguise.webservices.beans.DgConnection;
import com.dataguise.webservices.beans.DgConstraints;
import com.dataguise.webservices.beans.DgCustomFunctionsBean;
import com.dataguise.webservices.beans.DgException;
import com.dataguise.webservices.beans.DgInvalidColumnDetails;
import com.dataguise.webservices.beans.DgKeyInfo;
import com.dataguise.webservices.beans.DgSynchDataStructure;
import com.dataguise.webservices.beans.MaskerProgressStatus;
import com.dataguise.webservices.beans.MaskerSummaryStatus;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CentralMaskingAgentDelegate", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/")
public interface CentralMaskingAgentDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns
	 *         java.util.List<com.dataguise.webservices.beans.masker.DgColumnInfo
	 *         >
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getColumns", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetColumns")
	@ResponseWrapper(localName = "getColumnsResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetColumnsResponse")
	public List<DgColumnInfo> getColumns(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns
	 *         java.util.List<com.dataguise.webservices.beans.masker.DgKeyInfo>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getReferences", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetReferences")
	@ResponseWrapper(localName = "getReferencesResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetReferencesResponse")
	public List<DgKeyInfo> getReferences(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSchemas", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetSchemas")
	@ResponseWrapper(localName = "getSchemasResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetSchemasResponse")
	public List<String> getSchemas(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTables", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetTables")
	@ResponseWrapper(localName = "getTablesResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetTablesResponse")
	public List<String> getTables(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Integer
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "testConnection", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.TestConnection")
	@ResponseWrapper(localName = "testConnectionResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.TestConnectionResponse")
	public Integer testConnection(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "createAndTestCustomFunction", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.CreateAndTestCustomFunction")
	@ResponseWrapper(localName = "createAndTestCustomFunctionResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.CreateAndTestCustomFunctionResponse")
	public String createAndTestCustomFunction(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") DgCustomFunctionsBean arg1)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDgLog", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetDgLog")
	@ResponseWrapper(localName = "getDgLogResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetDgLogResponse")
	public List<String> getDgLog(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @throws DgException
	 */
	@WebMethod
	@RequestWrapper(localName = "startDatabaseMasking", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.StartDatabaseMasking")
	@ResponseWrapper(localName = "startDatabaseMaskingResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.StartDatabaseMaskingResponse")
	public void startDatabaseMasking(
			@WebParam(name = "arg0", targetNamespace = "") DgMaskerTask arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @throws DgException
	 */
	@WebMethod
	@RequestWrapper(localName = "cancelMasking", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.CancelMasking")
	@ResponseWrapper(localName = "cancelMaskingResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.CancelMaskingResponse")
	public void cancelMasking(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         com.dataguise.webservices.beans.masker.MaskerProgressStatus
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMaskingProgressStatus", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetMaskingProgressStatus")
	@ResponseWrapper(localName = "getMaskingProgressStatusResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetMaskingProgressStatusResponse")
	public MaskerProgressStatus getMaskingProgressStatus(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<com.dataguise.webservices.beans.masker.
	 *         MaskerSummaryStatus>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMaskingSummaryStatus", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetMaskingSummaryStatus")
	@ResponseWrapper(localName = "getMaskingSummaryStatusResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetMaskingSummaryStatusResponse")
	public List<MaskerSummaryStatus> getMaskingSummaryStatus(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getLogContent", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetLogContent")
	@ResponseWrapper(localName = "getLogContentResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetLogContentResponse")
	public String getLogContent(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @throws DgException
	 */
	@WebMethod
	@RequestWrapper(localName = "clearLogContent", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.ClearLogContent")
	@ResponseWrapper(localName = "clearLogContentResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.ClearLogContentResponse")
	public void clearLogContent(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @return returns java.lang.String
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDefaultLogContent", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetDefaultLogContent")
	@ResponseWrapper(localName = "getDefaultLogContentResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetDefaultLogContentResponse")
	public String getDefaultLogContent() throws DgException;

	/**
	 * 
	 * @param arg0
	 * @throws DgException
	 */
	@WebMethod
	@RequestWrapper(localName = "clearDefaultLogContent", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.ClearDefaultLogContent")
	@ResponseWrapper(localName = "clearDefaultLogContentResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.ClearDefaultLogContentResponse")
	public void clearDefaultLogContent(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "truncateSchema", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.TruncateSchema")
	@ResponseWrapper(localName = "truncateSchemaResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.TruncateSchemaResponse")
	public boolean truncateSchema(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDatabases", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetDatabases")
	@ResponseWrapper(localName = "getDatabasesResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetDatabasesResponse")
	public List<String> getDatabases(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns
	 *         java.util.List<com.dataguise.webservices.beans.masker.DgConstraints
	 *         >
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllConstraintsInDB", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetAllConstraintsInDB")
	@ResponseWrapper(localName = "getAllConstraintsInDBResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetAllConstraintsInDBResponse")
	public List<DgConstraints> getAllConstraintsInDB(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns
	 *         java.util.List<com.dataguise.webservices.beans.masker.DgColumnData
	 *         >
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSampleRow", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetSampleRow")
	@ResponseWrapper(localName = "getSampleRowResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetSampleRowResponse")
	public List<DgColumnData> getSampleRow(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws DgException;

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<com.dataguise.webservices.beans.masker.
	 *         DgSynchDataStructure>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "loadSynchData", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.LoadSynchData")
	@ResponseWrapper(localName = "loadSynchDataResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.LoadSynchDataResponse")
	public List<DgSynchDataStructure> loadSynchData(
			@WebParam(name = "arg0", targetNamespace = "") DgConnection arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") int arg3,
			@WebParam(name = "arg4", targetNamespace = "") int arg4,
			@WebParam(name = "arg5", targetNamespace = "") int arg5)
			throws DgException;

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<com.dataguise.webservices.beans.masker.
	 *         DgErrorMessageDetails>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getErrorLog", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetErrorLog")
	@ResponseWrapper(localName = "getErrorLogResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetErrorLogResponse")
	public List<DgErrorMessageDetails> getErrorLog(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "changeMaskingAction", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.ChangeMaskingAction")
	@ResponseWrapper(localName = "changeMaskingActionResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.ChangeMaskingActionResponse")
	public boolean changeMaskingAction(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1)
			throws DgException;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<com.dataguise.webservices.beans.masker.
	 *         DgInvalidColumnDetails>
	 * @throws DgException
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getInvalidColumns", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetInvalidColumns")
	@ResponseWrapper(localName = "getInvalidColumnsResponse", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", className = "com.dataguise.webservices.beans.masker.GetInvalidColumnsResponse")
	public List<DgInvalidColumnDetails> getInvalidColumns(
			@WebParam(name = "arg0", targetNamespace = "") List<DgColumnDetails> arg0,
			@WebParam(name = "arg1", targetNamespace = "") DgConnection arg1)
			throws DgException;

}
