package com.dataguise.webservices.beans.masker;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CentralMaskingAgentService service = new CentralMaskingAgentService();
 * CentralMaskingAgentDelegate portType = service.getCentralMaskingAgentPort();
 * portType.getColumns(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CentralMaskingAgentService", targetNamespace = "http://MaskerAgent.webservices.dataguise.com/", wsdlLocation = "file:/D:/Enterprise_2011/trunk/dgAgent/WebRoot/WEB-INF/wsdl/CentralMaskingAgentService.wsdl")
public class CentralMaskingAgentService extends Service {

	private final static URL CENTRALMASKINGAGENTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.dataguise.webservices.beans.masker.CentralMaskingAgentService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.dataguise.webservices.beans.masker.CentralMaskingAgentService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/D:/Enterprise_2011/trunk/dgAgent/WebRoot/WEB-INF/wsdl/CentralMaskingAgentService.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/D:/Enterprise_2011/trunk/dgAgent/WebRoot/WEB-INF/wsdl/CentralMaskingAgentService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CENTRALMASKINGAGENTSERVICE_WSDL_LOCATION = url;
	}

	public CentralMaskingAgentService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CentralMaskingAgentService() {
		super(CENTRALMASKINGAGENTSERVICE_WSDL_LOCATION, new QName(
				"http://MaskerAgent.webservices.dataguise.com/",
				"CentralMaskingAgentService"));
	}

	/**
	 * 
	 * @return returns CentralMaskingAgentDelegate
	 */
	@WebEndpoint(name = "CentralMaskingAgentPort")
	public CentralMaskingAgentDelegate getCentralMaskingAgentPort() {
		return super.getPort(new QName(
				"http://MaskerAgent.webservices.dataguise.com/",
				"CentralMaskingAgentPort"), CentralMaskingAgentDelegate.class);
	}

}
