package com.dataguise.saas.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * DgSaasUserPlatforms generated by hbm2java
 */
@Entity
@Table(name = "dg_saas_user_platforms")
public class DgSaasUserPlatforms implements java.io.Serializable {

	private int id;
	private DgSaasUsers dgSaasUsers;
	private DgSaasDataPlatforms dgSaasDataPlatforms;

	public DgSaasUserPlatforms() {
	}

	public DgSaasUserPlatforms(int id, DgSaasUsers dgSaasUsers,
			DgSaasDataPlatforms dgSaasDataPlatforms) {
		this.id = id;
		this.dgSaasUsers = dgSaasUsers;
		this.dgSaasDataPlatforms = dgSaasDataPlatforms;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@TableGenerator(name="table_gen", table="dg_sequence_gen", pkColumnName="seq_col_name",
	valueColumnName="seq_col_value", pkColumnValue="dg_saas_user_platform", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="table_gen")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public DgSaasUsers getDgSaasUsers() {
		return this.dgSaasUsers;
	}

	public void setDgSaasUsers(DgSaasUsers dgSaasUsers) {
		this.dgSaasUsers = dgSaasUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "platform_id", nullable = false)
	public DgSaasDataPlatforms getDgSaasDataPlatforms() {
		return this.dgSaasDataPlatforms;
	}

	public void setDgSaasDataPlatforms(DgSaasDataPlatforms dgSaasDataPlatforms) {
		this.dgSaasDataPlatforms = dgSaasDataPlatforms;
	}

}
