package com.dataguise.saas.model;

// Generated 8 Nov, 2016 2:49:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DgSaasRestrictedEmails generated by hbm2java
 */
@Entity
@Table(name = "dg_saas_restricted_emails", uniqueConstraints = @UniqueConstraint(columnNames = "email_address"))
public class DgSaasRestrictedEmails implements java.io.Serializable {

	private int id;
	private String emailAddress;
	private Character restrictionType;
	private Date createts;
	private Date updatets;

	public DgSaasRestrictedEmails() {
	}

	public DgSaasRestrictedEmails(int id, String emailAddress, Date createts) {
		this.id = id;
		this.emailAddress = emailAddress;
		this.createts = createts;
	}

	public DgSaasRestrictedEmails(int id, String emailAddress,
			Character restrictionType, Date createts, Date updatets) {
		this.id = id;
		this.emailAddress = emailAddress;
		this.restrictionType = restrictionType;
		this.createts = createts;
		this.updatets = updatets;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "email_address", unique = true, nullable = false, length = 256)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "restriction_type", length = 1)
	public Character getRestrictionType() {
		return this.restrictionType;
	}

	public void setRestrictionType(Character restrictionType) {
		this.restrictionType = restrictionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createts", nullable = false, length = 29)
	public Date getCreatets() {
		return this.createts;
	}

	public void setCreatets(Date createts) {
		this.createts = createts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatets", length = 29)
	public Date getUpdatets() {
		return this.updatets;
	}

	public void setUpdatets(Date updatets) {
		this.updatets = updatets;
	}

}
