package com.dataguise.saas.model;

// Generated 8 Nov, 2016 2:49:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DgSaasUserPlatformSol generated by hbm2java
 */
@Entity
@Table(name = "dg_saas_user_platform_sol")
public class DgSaasUserPlatformSol implements java.io.Serializable {

	private int id;
	private DgSaasUsers dgSaasUsers;
	private DgSaasDataPlatforms dgSaasDataPlatforms;
	private DgSaasDataSolutions dgSaasDataSolutions;

	public DgSaasUserPlatformSol() {
	}

	public DgSaasUserPlatformSol(int id, DgSaasUsers dgSaasUsers,
			DgSaasDataPlatforms dgSaasDataPlatforms,
			DgSaasDataSolutions dgSaasDataSolutions) {
		this.id = id;
		this.dgSaasUsers = dgSaasUsers;
		this.dgSaasDataPlatforms = dgSaasDataPlatforms;
		this.dgSaasDataSolutions = dgSaasDataSolutions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public DgSaasUsers getDgSaasUsers() {
		return this.dgSaasUsers;
	}

	public void setDgSaasUsers(DgSaasUsers dgSaasUsers) {
		this.dgSaasUsers = dgSaasUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "platform_id", nullable = false)
	public DgSaasDataPlatforms getDgSaasDataPlatforms() {
		return this.dgSaasDataPlatforms;
	}

	public void setDgSaasDataPlatforms(DgSaasDataPlatforms dgSaasDataPlatforms) {
		this.dgSaasDataPlatforms = dgSaasDataPlatforms;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "solution_id", nullable = false)
	public DgSaasDataSolutions getDgSaasDataSolutions() {
		return this.dgSaasDataSolutions;
	}

	public void setDgSaasDataSolutions(DgSaasDataSolutions dgSaasDataSolutions) {
		this.dgSaasDataSolutions = dgSaasDataSolutions;
	}

}
