package com.dataguise.saas.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DgSaasDataPlatforms generated by hbm2java
 */
@Entity
@Table(name = "dg_saas_data_platforms")
public class DgSaasDataPlatforms implements java.io.Serializable {

	private int id;
	private String dataPlatform;

	public DgSaasDataPlatforms() {
	}

	public DgSaasDataPlatforms(int id, String dataPlatform) {
		this.id = id;
		this.dataPlatform = dataPlatform;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "data_platform", nullable = false, length = 100)
	public String getDataPlatform() {
		return this.dataPlatform;
	}

	public void setDataPlatform(String dataPlatform) {
		this.dataPlatform = dataPlatform;
	}

}
