package com.dataguise.saas.model;

// Generated 8 Nov, 2016 2:49:02 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DgSaasRestrictedDomains generated by hbm2java
 */
@Entity
@Table(name = "dg_saas_restricted_domains", uniqueConstraints = @UniqueConstraint(columnNames = "domain_name"))
public class DgSaasRestrictedDomains implements java.io.Serializable {

	private int id;
	private String domainName;
	private Boolean needsApproval;
	private Date createts;
	private Date updatets;

	public DgSaasRestrictedDomains() {
	}

	public DgSaasRestrictedDomains(int id, String domainName, Date createts) {
		this.id = id;
		this.domainName = domainName;
		this.createts = createts;
	}

	public DgSaasRestrictedDomains(int id, String domainName,
			Boolean needsApproval, Date createts, Date updatets) {
		this.id = id;
		this.domainName = domainName;
		this.needsApproval = needsApproval;
		this.createts = createts;
		this.updatets = updatets;
	}

	@Id 
	@Column(name="id",  nullable=false)
	@TableGenerator(name="table_gen", table="dg_sequence_gen", pkColumnName="seq_col_name",
	valueColumnName="seq_col_value", pkColumnValue="dg_saas_restri_dom_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="table_gen")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "domain_name", unique = true, nullable = false, length = 254)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "needs_approval")
	public Boolean getNeedsApproval() {
		return this.needsApproval;
	}

	public void setNeedsApproval(Boolean needsApproval) {
		this.needsApproval = needsApproval;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createts", nullable = false, length = 29)
	public Date getCreatets() {
		return this.createts;
	}

	public void setCreatets(Date createts) {
		this.createts = createts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatets", length = 29)
	public Date getUpdatets() {
		return this.updatets;
	}

	public void setUpdatets(Date updatets) {
		this.updatets = updatets;
	}

}
