package com.dataguise.util;

public enum ErrorConstants {
	INVALID_SESSION("1050", "Session is no longer valid", "error message from Controller"),
	CONNECTION_ALLOWED_LICENSE("6777", "Total Number of connections has increased as allowed by the active license","Total Number of connections has increased as allowed by the active license"),
	BAD_INPUT("1070", "Message from UI to Controller was bad", "error message from Controller"),
	REPO_INTERNAL_ERROR("1000", "Internal Error with Metadata Repository", "error message from Repository"),
	MASKER_AGENT_ERROR("1080", "Masker Agent Error", "Error message from Masker Agent"),
	MASKER_AGENT_SQL_ERROR("1090", "SQLException", "SQLException"),
	DISCOVER_DIFF_FIRSTINST_ERROR("1100", "First Instance doesn't exist","Discover diff report" ),
	DISCOVER_DIFF_SECONDINST_ERROR("1110", "Second Instance doesn't exist", "Discover diff report"),
	DISCOVER_DIFF_BOTHINST_ERROR("1120", "Both Instances don't exist","Discover diff report"),
	DISCOVER_DIFF_DIFFTASK_ERROR("1130", "Both Instances don't point to the same task definition", "Discover diff report" ),
	SAVE_DATA_ERROR("1140", "Error saving discovery results", "Error while saving discovery results" ),
	SAVE_RESULT_ERROR("1150", "Error saving discovery Status", "Error while saving discovery Status" ),
	STALE_DATA_ERROR("1160", "The record has been recently updated in a parallel session, Kindly refresh your page.", "Record has already been updated. Please refresh"),
	LOAD_DATABASE_FIND_RESULTS_DETAILS_ERROR("4010","Error loading task results","error message from Repository"),
	START_DATABASE_FIND_TASK_ERROR("4020","Error in starting the task","error message from agent"),
	//GET_NMAP_TASK_NAME_FROM_INSTANCE_ID_ERROR("4030","Error in getting Nmap task name from instance id","error message from Repository"),
	//DELETING_TASK_NAME_ERROR("4040","Error in deleting find it task","error message from Repository"),
	SAVE_DATABASE_FIND_TASK_ERROR("4050","Error saving task","error message from Repository"),
	DEACTIVATE_ROLE_ERROR("1141", "Unable to deactivate role as users having same role already exists", "Unable to deactivate role as users having same role already exists" ),
	AUTHENTICATION_ERROR("5000","Authentication Error","error message from Controller"),
	AUTHENTICATION_ERROR_BLANK_PASS("5001","Authentication Error: null or blank Password","error message from Controller"),
	LOGOUT_ERROR("5010","Error logging out","error message from Controller"),
	INACTIVE_USER("5020","User is in inactive state","error message from Controller"),
	MASKER_TASK_SAVE_ERROR("6010","Error saving masker task","error message from Controller"),
	MASKER_SAVED_TASK_ERROR_WITHOUT_MASKING("6011", "Please apply masking on available columns", "Please apply masking on available columns"),
	MASKER_TASK_LOAD_ERROR("6020","Error loading masker task","error message from Controller"),
	LOAD_SENSITIVE_COLUMNS_ERROR("6021","Error in loading sensitive columns for DB","error message from Controller"),
	PAUSE_RESUME_SUPPORTED_ERROR("6022","This database does not support pause/resume functionality","error message from Controller"),
	MASKER_TASK_START_ERROR("6030","Error starting masker task","error message from Controller"),
	SQOOP_TASK_START_ERROR("6031","Error starting sqoop task","error message from Controller"),
	MASKER_GET_RESULTS_ERROR("6040","Error getting results for masker task","error message from Controller"),
	SQOOP_GET_RESULTS_ERROR("6041","Error getting results for sqoop task","error message from Controller"),
	MASKER_GET_STATUS_ERROR("6050","Error getting status of masker task","error message from Controller"),
	MASKER_MASKING_ALREADY_RUNNING_ERROR("6060","Start Masker task failed, Masking already running on this server","error message from Controller"),
	START_SENSITIVE_DATA_DISCOVERY_TASK_ERROR ("7000", "Error starting discover task", "error message from Controller"),
	START_HDFS_TASK_ERROR ("7005", "Error starting HDFS task", "error message from Controller"),
	SAVE_HDFS_TASK_ERROR ("7006", "Error saving HDFS task", "error message from Controller"),
	GET_DATABASES_FOR_CONNECTION_ERROR ("7010", "Error in getting database list for connection", "error message from Agent"),
	LICENSE_FILE_READ_WRITE_ERROR ("7020", "Error in read/write license file", "error message from servlet"),
	ERROR_VERIFYING_LICENSE ("7025", "Error in verifying the license", "error message from Controller"),
	GETTING_INSTALLED_LICENSES_ERROR ("7030", "Error in getting installed licenses", "error message from servlet"),
	ERROR_INSTALLING_LICENSE ("7035", "Could not install license. Please check the file name and path", "error message from Controller"),
	ERROR_FINDING_LICENSE ("7038", "Could not find the license file. Please check the file name and path", "error message from Controller"),
	ERROR_NO_LICENSE_INFO ("7039", "No license information exists.", "error message from Controller"),
	ERROR_IN_CONFIGURING_AGENT("7040", "Error in adding/updating/deleting dgAgent", "error message from servlet"),
	ERROR_GETTING_AGENT_TYPE("7041","Error in getting the agent types","Error in getting the agent types"),
    ERROR_EMPTY_USER_NAME("7942", "User Name can not be empty","User Name can not be empty"),
	ERROR_GETTING_DGAGENTS ("7050", "Error in getting existing agents", "error message from servlet"),
	ERROR_GETTING_PRODUCTNAMES ("7060", "Error in getting installed product names", "error message from servlet"),
	ERROR_IN_USE ("1060", "Item being deleted is in use", "error message from Controller"),
	ERROR_VERIFY_ROLE ("8000", "Error in verifying role", "error message from Controller"),
	ERROR_CREATING_USER ("8001", "Error in creating/updating user", "error message from Controller"),
	ERROR_UPDATING_USER ("8005", "Error in updating user", "error message from Controller"),
	ERROR_ADD_UPDATE_USER("8006","Error in create/update user as it exceeds the no of users allowed", "Error in create/update user as it exceeds the no of users allowed"),
	ERROR_CHALLENGE_PASSWORD ("8010", "Invalid challenge password", "error message from Controller"),
	ERROR_USER_CREDENTIALS ("8020", "Invalid user name or password", "error message from Controller"),
	ERROR_GETTING_USERS ("8030", "Unable to retrieve users", "error message from Controller"),
	ERROR_GETTING_ROLES ("8040", "Internal Error: Unable to retrieve roles", "error message from Controller"),
	ERROR_INVALID_COMMAND ("8050", "Internal Error: Invalid Command", "error message from Controller"),
	ERROR_INVALID_AGENT_NAME ("8060", "Internal Error: Invalid Agent Name Specified", "error message from Controller"),
	SAVE_ROLE_ERROR("1140", "Error creating role", "Error while saving role with permissions" ),
	SUPER_USER_ERROR ("8080", "Not a valid Super user", "Invalid Super user"),
	SYSTEM_STATUS_ERROR ("8090", "Errror getting system status", "Controller error"),
	NULL_INPUT ("9000", "Not a valid parameter", "Invalid input") ,
	SAVE_TASK_DEFINITIONS_ERROR("8085", "Error while allocating permissions for task definitions as per provided role", "Error while allocating permissions for task definitions as per provided role" ),
	SAVE_PRODUCT_ERROR("8095", "Error while allocating permissions for products as per provided role", "Error while allocating permissions for products as per provided role" ),
	INVALID_TASK("9010","Invalid Task","Invalid Task to start"),
	INVALID_URL("9011","Invalid URL","Invalid URL"),

	CONSTRAINT_VIOLATION_ERROR("2000", "The name is already being used in the system, Please provide a different name", "Constraint Violation Error"),
	TEST_CONNECTION_ERROR("2010", "Could not connect to database server", "Could not connect to database server"),
	ERROR_CREATING_CONNGRP ("2020", "Error in creating/updating connection group", "error message from Controller"),
	ERROR_LOADING_CONNGRP ("2030", "Error in loading connection groups", "error message from Controller"),
	ERROR_CREATING_IPRANGE ("2040", "Error in creating/updating IP Range", "error message from Controller"),
	INVALID_IPRANGE ("3000", "Not a valid IP range", "error message from Controller"),

	ERROR_LOADING_IPRANGE ("2050", "Error in loading IP Range", "error message from Controller"),
	ERROR_UNABLE_TO_RESOLVE_HOSTNAME ("2051", "Unable to resolve Hostname. Kindly update IP Address field in Connection Details.", "Unable to resolve Hostname. Kindly update IP Address field in Connection Details."),
	ERROR_ASSIGNING_IPRANGE ("2060", "Error in assigning Ip Range to Agent", "error message from Controller"),
	ERROR_ASSIGNING_DBTYPE ("2070", "Error in assigning DB Type to connection group", "error message from Controller"),
	ERROR_CREATING_DBTYPE ("2080", "Error in creating/updating DB Type", "error message from Controller"),
	ERROR_LOADING_DBVENDORS ("2090", "Error in loading connection DB vendors", "error message from Controller"),
	ERROR_LOADING_DBTYPES ("1170", "Error in loading DB Types", "error message from Controller"),
	ERROR_SAVING_CONNECTIONS ("1180", "Error in saving connections for Connection group", "error message from Controller"),
	ERROR_LOADING_CONNECTIONS ("1190", "Error in loading connections for Connection group", "error message from Controller"),
	ERROR_SAVING_DBATTRIBUTES("1200", "Error in saving database attributes", "error message from Controller"),
	ERROR_ENCRYPTING_DATA("1340", "Error while encrypting data", "error message from controller") ,
	ERROR_CREATE_ACCESS("1300", "User does not have rights to create a new record", "User does not have rights to create records"),
	ERROR_DELETE_ACCESS("1310", "User does not have rights to delete this record", "User does not have rights to delete this connection record"),

	ERROR_UPDATE_ACCESS("1320", "User does not have rights to update this record", "User does not have rights to update this record"),
	ERROR_EXECUTE_ACCESS("1330", "User does not have rights to execute this task", "User does not have rights to execute this task"),
	ERROR_DB_CREDENTIALS("3010", "Invalid Database credentials", "Invalid Database credentials"),
	ERROR_TNS_CREDENTIALS("3020", "Please set tns_admin or oracle_home system variable", "Please set tns_admin or oracle_home system variable"),
	ERROR_DBATRTHREAD ("1400", "Error in DBAttributesControl Servlet", "error message from Controller"),
	ERROR_CONNECT_DISCOVER_AGENT("1210", "Unable to connect discover agent", "Unable to connect discover agent"),
	ERROR_CONNECT_MASKER_AGENT("1220", "Unable to connect masker agent", "Unable to connect  masker agent"),
	ERROR_CONNECT_SQOOP_AGENT("1221", "Unable to connect sqoop agent", "Unable to connect  sqoop agent"),
	ERROR_CONNECT_HADOOP_AGENT("1225", "Unable to connect hadoop agent", "Unable to connect  hadoop agent"),
	ERROR_GETTING_HADOOP_RESULTS("1227", "Unable to get hadoop discovery results", "Unable to get hadoop discovery results"),
	ERROR_CONNECT_HADOOP_MASKER_AGENT("1226", "Unable to connect hadoop masker agent", "Unable to connect  hadoop masker agent"),
	ERROR_CONNECT_FILE_DISCOVER_AGENT("1228", "Unable to connect to File Discover agent", "Unable to connect to File Discover agent"),
	SUPERADMIN_NOT_LOGGED_IN("1230", "Session is no longer valid.Please Log in again as super user..", "Session is no longer valid.Please Log in again as super user.."),
	INCOMPATIBLE_COLUMN_DATA_TYPE("1240", "Incompatible column data type", "Incompatible column data type"),

	MULTIPLE_AGENT_POINTERS("1250", "Connection groups and Connections point to multiple agents", "Connection groups and Connections point to multiple agents"),
	UNABLE_TO_CONTACT_DISCOVER_AGENT("1260","Unable to contact Discover Agent","Unable to contact Discover Agent"),
	NO_MASKER_AGENT_CONFIGURED("1270","No masker agent has been configured","No masker agent has been configured"),
	NO_HADOOP_AGENT_CONFIGURED("1272","No hadoop agent has been configured","No hadoop agent has been configured"),
	NO_DISCOVER_AGENT_CONFIGURED("1271","No Discover agent has been configured","No Discover agent has been configured"),
	NO_MONITORING_AGENT_CONFIGURED("1273","No monitoring agent has been configured","No monitoring agent has been configured"),
	NO_SQOOP_AGENT_CONFIGURED("1274","No sqoop agent has been configured","No sqoop agent has been configured"),
	CANNOT_UPDATE_SUPER_ADMIN_ROLE("1280","Cannot update role. At least one user with Super-Admin role is required","Cannot update role. At least one user with Super-Admin role is required"),
	SUPERADMIN_NOT_ALLOWED_TO_UPDATE("1290","Privileges for the SUPER_ADMIN role cannot be modified.","Privileges for the SUPER_ADMIN role cannot be modified."),
	ASSIGN_SAME_TYPE_AGENT("1325","IP Range already assigned to this type of agent.","IP Range already assigned to this type of agent."),
	USER_ALREADY_EXISTS("1350","User Name already exists","User Name already exists"),
	ERROR_INSERT_ATTRIBUTE("1400","Error in inserting attribute  info","Error in inserting attribute  info"),
	ERROR_LOADING_ATTRIBUTE("1401","Error in loading  attribute  info","Error in loading attribute  info"),
	ERROR_LOADING_DATABASE("1402","Error in  loading database  info","Error in  loading database   info"),
	ERROR_INSERTING_DATABASE("1403","Error in  loading database  info","Error in  loading database   info"),
	ERROR_INSERTING_HADOOP_DIR_INFO("1407","Error inserting hadoop dir info","Error inserting hadoop dir info"),
	ERROR_LOADING_ATTRIBUTETYPE("1404","Error in  loading attribute type","Error in  loading attribute type"),
	ERROR_LOADING_NOTIFICATION("1408","Error in  loading notification","Error in  loading notification"),
	ERROR_LOADING_ROLES_FOR_NOTIFICATION("1410","Error in  loading roles for notification","Error in loading roles for notification"),
	ERROR_INSERTING_ROLES_FOR_NOTIFICATION("1410","Error in  inserting roles for notification","Error in inserting roles for notification"),
	ERROR_UPDATING_ROLES_FOR_NOTIFICATION("1410","Error in  updating roles for notification","Error in updating roles for notification"),
	ERROR_DELETING_ROLES_FOR_NOTIFICATION("1410","Error in  deleting roles for notification","Error in deleting roles for notification"),
	ERROR_LOADING_SMTP_DETAILS("1408","Error in loading SMTP details","Error in loading SMTP details"),
	ERROR_DELETE_ATTRIBUTE("1405","Error in  deleting attribute","Error in  deleting attribute"),
	ERROR_UPDATE_ATTRIBUTE("1406","Error in  updating attribute","Error in  updating attribute"),
	ERROR_UPDATE_NOTIFICATION("1409","Error in  updating notification","Error in  updating notification"),
	ERROR_SENDING_NOTIFICATION("1412","Error in  sending notification","Error in  sending notification"),
	ERROR_LOADING_SHARABILITY_NOTIFICATION("1409","Error in  loading sharability for notification","Error in  loading sharability for notification"),
	ROLE_NOTIFICATION_ALREADY_EXIST("1411","Role is already mapped to this notification","Role is already mapped to this notification"),
	ERROR_TEST_NOTIFICATION("1410","Error in  testing SMTP Configurations","Error in  testing SMTP Configurations"),
	ERROR_SAVING_SMTP_DETAILS("1409","Error in  saving SMTP details","Error in  saving SMTP details"),
	ERROR_AUTHENTICATING_SMTP_DETAILS("1408","Error in  authenticating SMTP details","Error in  authenticating SMTP details"),
	UNABLE_TO_REACH("7011", "System is unable to reach the database ", "error message from Agent"),
	DISCOVER_COMMON_FIRSTINST_ERROR("1360", "First Instance doesn't exist","Discover common report" ),
	DISCOVER_COMMON_SECONDINST_ERROR("1370", "Second Instance doesn't exist", "Discover common report"),
	DISCOVER_COMMON_BOTHINST_ERROR("1380", "Both Instances don't exist","Discover common report"),
	DISCOVER_COMMON_DIFFTASK_ERROR("1390", "Both Instances don't point to the same task definition", "Discover common report" ),
	DUPLICATE_ROLE("1150", "Role name already exists", "Role name already exists" ),
	ERROR_NETWORK_MAP_CREDENTIALS("3015", "Invalid Network Mapping credentials", "Invalid Network Mappingcredentials"),
	ERROR_RETRIEVE_BRANDING ("1111", "Error in retrieving branding", "Error in retrieving branding"),
	CANNOT_UPDATE_SINGLE_ACTIVE_LICENSE("2222","Cannot update License. At least one License needs to be active","Cannot update License. At least one License needs to be active"),
	ERROR_LICENSE_INFO("3333","Error in finding license Information","Error in finding license Information"),
	START_FILE_DATA_DISCOVERY_TASK_ERROR ("7010", "Error starting File task", "error message from Controller"),
	CANCEL_FILE_TASK_ERROR("7012" , "Error in cancelling task" ,"Error in cancelling task"),
	ERROR_OUTPUT_DIRECTORY_EXISTS("7013", "Output Directory exists for the connection", "Output Directory exists for the connection"),

	OVERLAP_IPRANGE ("4444", "IP Range Overlap with existing Range", "error message from Controller"),
	ERROR_DISCOVER_SENSITIVITY_FOR_COLUMN("1100", "Error in getting sensitivity for column", "Error in getting sensitivity for column" ),
	ERROR_IN_CONFIGURING_DG_FLUME_AGENT("3011", "Error in configuring DgFlume agent", "Error in configuring DgFlume agent"),
	ERROR_IN_SAVING_DG_FLUME_TEMPLATE_PATTERN("3012", "Error in saving dgFlume template pattern", "Error in saving dgFlume template pattern"),
	ERROR_IN_SAVING_DG_FLUME_TEMPLATE("3014", "Error in saving dgFlume template", "Error in saving dgFlume template"),
	ERROR_IN_FETCHING_DG_FLUME_TEMPLATE_PATTERN("3016", "Error in fetching dgFlume template ", "Error in fetching dgFlume template"),
	ERROR_IN_FETCHING_DG_FLUME_AGENTS("3013", "Error in fetching dgFlume agents ", "Error in fetching dgFlume agents"),
	NO_CORRESPONDING_AGENT("3020", "No corresponding agent found, please make sure Ip ranges are defined properly and assigned to the agents", "No corresponding agent found, please make sure Ip ranges are defined properly and assigned to the agents"),
	SOME_CONNS_DONOT_HAVE_AGENT("3030", "Some connections do not belong to any agent", "Some connections do not belong to any agent"),
	ERROR_IN_CONFIGURING_NOTIFICATIONS("3031", "Error in configuring notifications", "Error in configuring notifications"),

	ERROR_IN_CONFIGURING_DG_FTP_AGENT("3035", "Error in configuring DgFtp agent", "Error in configuring DgFtp agent"),

	ERROR_IN_SAVING_DG_FTP_TEMPLATE_PATTERN("3040", "Error in saving DgFtp template pattern", "Error in saving DgFtp template pattern"),
	ERROR_IN_SAVING_DG_FTP_TEMPLATE("3041", "Error in saving DgFtp template", "Error in saving DgFtp template"),

	ERROR_IN_FETCHING_DG_FTP_TEMPLATE_PATTERN("3045", "Error in fetching DgFtp template ", "Error in fetching DgFtp template"),
	ERROR_IN_FETCHING_DG_FTP_AGENTS("3050", "Error in fetching DgFtp agents ", "Error in fetching DgFtp agents"),
	ERROR_IN_MASKING_OPTIONS("3055","Maksing options for selected Expressions are blank","Maksing options for selected Expressions are blank"),
	ERROR_IN_FETCHNG_AGENTS_STATUS("3060","Error in fetching agent status","Error in getting agent status"),
	ERROR_IN_CLEARING_CACHE("3056","Error in clearing cache","Error in clearing cache"),
	ERROR_INSERT_DOMAIN("1600","Error in saving Domain info","Error in saving domain info"),
	ERROR_UPDATE_DOMAIN("1601","Error in updating domain","Error in updating domain"),
	ERROR_LOADING_DOMAIN("1602","Error in loading domain info","Error in loading domain info"),
	ERROR_LOADING_POLICY("1603","Error in loading policy info","Error in loading policy info"),
	ERROR_ASSIGN_POLICY("1604","Error in assigning policy","Error in assigning policy"),
	ERROR_ASSIGN_DIRECTORY("1605","Error in assigning directory","Error in assigning directory"),
	ERROR_DELETE_DOMAIN("1606","Error in deleting domain","Error in deleting domain"),
	ERROR_DELETE_DIR("1607","Error in deleting directory","Error in deleting directory"),
	ERROR_VERIFYING_TASK_POLICY("1608","Error Verifying Task Policy","Error Verifying Task Policy"),
	ERROR_CREATING_DGCOL_FILE("1609","Error Creating dgCol File","Error Creating dgCol File"),
	ERROR_ASSIGNING_DIRECTORY_TO_STRUCTURE("1610","Directory Path already assigned to a structure","Directory Path already assigned to a structure"),
	ERROR_ADDING_COLUMN_TO_STRUCTURE("1611","Error in adding Columns to the Structure.","Error in adding Columns to the Structure."),
	PATH_NOT_PART_OF_DOMAIN("1612","Scan path-Domain error","Scan path-Domain error"),
	ERROR_DOWNLOAD_POLICY("1613","Error in downloading Policy","Error in downloading Policy"),
	ERROR_UPLOAD_POLICY("1613","Error in uploading Policy","Error in uploading Policy"),
	TASK_TYPE_DESCRIPY("1615","Unable to run structural task. Please make sure each scan path is associated to some structure.","Unable to run structural task. Please make sure each scan path is associated to some structure."),
	ERROR_ASSIGNING_DIRECTORY_TO_TASK("1616","Directory Path is already assigned to some other task.","Directory Path is already assigned to some other task."),
	VALIDATE_SAVE_MASKER_TASK_ERROR("1621","Error Validatiing user data", "Error Validating user data"),
	POLICY_CONFLICT_ERROR("1622","Duplicate Expressions in multiple policies", "Duplicate Expressions in multiple policies"),
	NO_SENSITIVE_ITEMS_FOUND_ERROR("1623","No sensitive items found for selected Databases/Schemas","No sensitive items found for selected Databases/Schemas"),
	AGENT_NOT_FOUND("3019", "No corresponding agent found", "No corresponding agent found"),
	ERROR_DELETE_ENCRYPT_DIR("3021","Error deleting Encryption directory","Error deleting Encryption directory"),
	ERROR_INSERT_ENCRYPT_DIR("3022","Error in saving Encryption directory","Error in saving Encryption directory"),
	ERROR_UPDATE_ENCRYPT_DIR("3023","Error in updating Encryption directory","Error in updating Encryption directory"),
	ERROR_LOADING_ENCRYPT_DIR("3024","Error in loading Encryption directory","Error in loading Encryption directory"),
	ERROR_DELETE_MASKING_DIR("3025","Error deleting Masking directory","Error deleting Masking directory"),
	ERROR_INSERT_MASKING_DIR("3026","Error in saving Masking directory","Error in saving Masking directory"),
	ERROR_UPDATE_MASKING_DIR("3027","Error in updating Masking directory","Error in updating Masking directory"),
	ERROR_LOADING_MASKING_DIR("3028","Error in loading Masking directory","Error in loading Masking directory"),
	ERROR_ENCRYPT_DIR_SAME_SCAN_DEST("3029","Scan path and Destination path cannot be identical","Scan path and Destination path cannot be identical"),
	ERROR_ENCRYPT_BRANCH_BELOW_SCAN("3030","Branch point should not be specified below scan path","Branch point should not be specified below scan path"),
	ERROR_ENCRYPT_DEST_BELOW_SCAN("3031","Destination path should not be at or below Scan path","Destination path should not be at or below Scan path"),
	WARNING_OUTPUT_DIR_INFO_NOT_SPECIFIED("3032","Output dir for some scan path is not specified.","Output dir for some scan path is not specified."),
	MASK_TEMPLATE_LOAD_ERROR("6081","Error loading mask template","error message from Controller"),
	ERROR_SAVING_SEQUENCE_FILE ("3033","Error saving sequence file","Error saving sequence file"),
	ERROR_UNSUPPORTED_SEQUENCE_FILE ("3035","Error parsing file, only JAR file supported","Error parsing file,only JAR file supported"),
	ERROR_GETTING_SEQUENCE_FILE_FIELDS ("3034","Error getting fields from sequence file","Error getting fields from sequence file"),
	ERROR_DELETE_DECRYPT_DIR("3035","Error deleting Decryption directory","Error deleting Decryption directory"),
	ERROR_INSERT_DECRYPT_DIR("3036","Error in saving Decryption directory","Error in saving Decryption directory"),
	ERROR_UPDATE_DECRYPT_DIR("3037","Error in updating Decryption directory","Error in updating Decryption directory"),
	ERROR_LOADING_DECRYPT_DIR("3038","Error in loading Decryption directory","Error in loading Decryption directory"),
	ERROR_SENDING_EMAILS("4444","Error in sending emails","Error in in sending emails"),
	ERROR_SAVING_ACL_FILE("3039","Error saving ACL file on HDFS","Error saving ACL file on HDFS"),
	SPECIAL_CHARS_NOT_ALLOWED("4500", "Name having special characters or starting with number are not allowed", "Name having special characters or starting with number are not allowed"),
	SPECIAL_CHARS_SPACE_NOT_ALLOWED("4501", "Name having special characters, having spaces or starting with number are not allowed", "Name having special characters, having spaces or starting with number are not allowed"),
	JSON_PARSING_ERROR("5000", "Unable to parse the JSON", "JSON parse error"),
	INVALID_TASK_TYPE("5001", "Invalid task type", "Invalid task type"),
	ERROR_IMPORT_STRUCTURE("1614","Error in importing structure for the given file","Error in importing structure for the given file"),
	ERROR_HASH_VALUE("5002","Unable to get hash value","Unable to get hash value"),
	OLD_PASS_INCORRECT("5003","Incorrect old password","Incorrect old password"),
	RESET_LINK_EXPIRED("5004","Reset password link is expired","Reset password link is expired"),
	UNABLE_FIND_USER("5005","Unable to find the specified user","Unable to find the specified user"),
	USER_EMAIL_NOTSET("5006","User email id not found","User email id not found"),
	LINK_INVALID("5007","Not a valid link for this user","Not a valid link for this user"),
	ERROR_UNSUPPORTED_AVRO_FILE("3042", "Error getting fields from avro file","Error getting fields from avro file"),
	ERROR_SAVING_AVRO_FILE("3043", "Error saving fields from avro file","Error saving fields from avro file"),
	STRUCTURE_VERIFICATION_ERROR("5002", "Structure verification error", "Structure verification error"),
	FILE_PATH("5003" , "File Path Does not Exist" ,"File Path Does not Exist"),
	STRUCTURE_IN_USE("5556","Structure cannot be deleted as it is in use","Structure cannot be deleted as it is in use"),
	STRUCTURE_CHECK_ERROR("5555","Unstructured operations are not allowed on ORC/RC files.","Unstructured operations are not allowed on ORC/RC files."),
	EMPTY_STRUCTURE_SAVE_ERROR("5557","Cannot save empty structure.Select atleast one Expression Type.","Cannot save empty structure.Select atleast one Expression Type."),
	TRAVERSE_STRUCTURE_ERROR("5558", "Error in traversing the structure.","Error in traversing the structure."),
	ERROR_ADD_DIFFERENT_AVRO_STRUCTURE("5559","Cannot associate more then one type of Avro Structure with one task.","Cannot associate more then one type of Avro Structure with one task."),
	ERROR_ADD_DIFFERENT_SEQ_STRUCTURE("5560","Cannot associate more then one type of Sequence Structure with one task.","Cannot associate more then one type of Sequence Structure with one task.") ,
	ERROR_DELETING_CUSTOM_FUNCTION("5561","Custom Function is in use","Custom Function is in use"),
	ERROR_SAVING_HDFS_TASK_NO_STRUCTURE_ASSOCIATED("5562","'Structured' task cannot be saved because no structure is associated with the specified scan path(s)","'Structured' task cannot be saved because no structure is associated with the specified scan path(s)"),
	ERROR_GETTING_TASK_SCANPATH_SNAPSHOT("5563","Unable to get task scan-path snapshot object, most likely there is some path mismatch between results path and task scan-path","Unable to get task scan-path snapshot object, most likely there is some path mismatch between results path and task scan-path"),
	EMPTY_STRUCTURE_SAVE_TASK_ERROR("5564","Cannot save task with empty structure or with no Expression Type with a Buildin Types Sequence Structures.","Cannot save task with empty structure or with no Expression Type with a Buildin Types Sequence Structures"),
	ERROR_SAVING_HDFS_TASK_NO_POLICY_FOR_FPD("5565","Task cannot be saved because no policy is associated with the specified Task Type ","Task cannot be saved because no policy is associated with the specified Task Type"),
	BLANK_EXPRESSION_TYPE_SELECT_ERROR("5566","Cannot add the columns with blank Expression Type.","Cannot add the columns with blank Expression Type."),
	DIRECTORY_IN_USE("5567","The Directory or its Parent Directory is already mapped to structure.","The Directory or its Parent Directory is already mapped to  structure."),
	HADOOP_VALIDATION_EXPRESSION_ERR("5568","Individual expressions cannot be selected","Task Validation Failed"),
	HADOOP_VALIDATION_POLICY_ERR("5569","Policy must be specified","Task Validation Failed"),
	HADOOP_VALIDATION_DOMAIN_ERR("5570","Scan path should be part of a domain","Task Validation Failed"),
	NO_CORRESPONDING_IPRANGE("5571", "No corresponding IP Range found, please make sure the same Ip ranges are defined and assigned to the agents/tasks accordingly.", "No corresponding IP Range found, please make sure the same Ip ranges are defined and assigned to the agents/tasks accordingly."),
	TASK_DOESNOT_EXISTS("5572","Specified task doesnot exists","Specified task doesnot exists"),
	PATH_NOT_FOUND("5573","Either destination path is not valid or user doesn't have write permission to this directory ","Either destination path is not valid or user doesn't have write permission to this directory "),
	ERROR_UPDATE_CONNECTION("5574","Error in  updating connection","Error in  updating connection"),
	BLANK_DELIMETER_PATTERN("5575","Cannot save structure with empty column delimeter or file pattern","Cannot save structure with empty column delimeter or file pattern"),
	ERROR_IN_READING_REFERENCED_DATATYPE_FILE("5576","Error in reading referenced datatype file","Error in reading referenced datatype file"),
	ERROR_GETTING_STRUCT_DETAIL("5577","Error in getting the structure detail.","Error in getting the structure detail."),
	ERROR_FINDING_RC_STRUCTURE("5578","Error in finding the multi RC structure","Error in finding the multi RC structure"),
	FLUME_TASK_VALIDATION_POSITIONAL_STRUCTURE("5579","Only Masking is allowed with positional structure definition.","Only Masking is allowed with positional structure definition."),
	HDFS_TASK_VALIDATION_POSITIONAL_STRUCTURE("5580","Only Discover and Masking Task type are allowed with positional structure.","Only Discover and Masking Task type are allowed with positional structure."),
	HDFS_TASK_VALIDATION_OUTPUT_COLUMN("5581","Only \"Replace\" is allowed as Output Column with positional structure.","Only \"Replace\" is allowed as Output Column with positional structure."),
	HADOOP_VALIDATION_POLICY_ERR_CONSISTENT_MASK("5582","Policy must be specified for Consistent Masking.","Policy must be specified for Consistent Masking."),
	HADOOP_VALIDATION_SCANPATH_DOMAIN_ERR("5583","Scan path must be associated with domain.","Scan path must be associated with domain."),
	ERROR_UPDATING_REFERENCE_DATA("5584","Error updating reference data path" , "Error updating reference data path"),
	AGENT_ALLOWED_LICENSE("5585", "Total Number of agents has increased as allowed by the active license","Total Number of agents has increased as allowed by the active license"),
	ERROR_LOGIN_FAILED("5598","Login failed","Login failed"),
	KEY_NAME_SAME_VALUE_HIVEMAP("5599","Cannot save HiveMap Structure with keys having same name.","Cannot save HiveMap Structure with keys having same name."),
	FLUME_FTP_TASK_VALIDATION_STRUCTURE("5600","Discovery or Row Encryption is not allowed with structure definition.","Discovery or Row Encryption is not allowed with structure definition."),
	HIVE_GET_TABLES_ERROR("5586", "Error in getting the Hive Tables Data","Error in getting the Hive Tables Data"),
	HIVE_GET_DATABASE_ERROR("5587", "Error in getting the Hive Databases","Error in getting the Hive Databases"),
	HIVE_GET_COLUMNS_ERROR("5588", "Error in getting the Hive Columns","Error in getting the Hive Columns"),
	HIVE_START_DISCOVERY_ERROR("5589", "Error in starting hive discovery task","Error in starting hive discovery task"),
	START_HIVE_DISCOVERY_TASK_ERROR ("5590", "Error starting Hive task", "Error starting Hive task"),
	START_HIVE_TASK_ERROR ("5591", "Error starting Hive task", "Error starting Hive task"),
	ERROR_CONNECT_HIVE_AGENT("5592", "Unable to connect hive agent", "Unable to connect  hive agent"),
	ERROR_PRODUCT_ACCESS("5593", "User does not have access to this product", "User does not have access to this product"),
	ERROR_STRUCTURE_DOMAIN_ACCESS("5593", "Default user can not create domain/structure. Please login with Super Admin user.", " Default user can not create domain/structure. Please login with Super Admin user."),
	ERROR_RESULT_VIEW_PERMISSIONS("5594","Access to given Task Instance denied" , "Access to given Task Instance denied"),
	ERROR_UNDEFINED_CONTROLLER_URL("5595","No controller url pushed for Agent","No controller url pushed for Agent"),
	ERROR_POLICY_DISCREPANCY("5596","Policy Discrepancy","Policy Discrepancy"),

	AGENT_CONFIG_MISMATCH("5601","There is configuration mismatch between both Hadoop agents","There is configuration mismatch between both Hadoop agents"),
	UNABLE_TO_GET_AGENT_DETAILS("5602","Failed to get Hadoop agent detailed info","Failed to get Hadoop agent detailed info"),
	UNABLE_TO_CONNECT_PRIMARY("5603","Unable to connect to primary Hadoop agent for this cluster","Unable to connect to primary Hadoop agent for this cluster"),
	UNABLE_TO_CONNECT_STANDBY("5604","Failed to connect both primary and standby Hadoop agent for this cluster","connect both primary and standby Hadoop agent for this cluster"),
	NO_STANDBY_AGENT_FOUND("5605","Failed to connect primary agent and unable to find standby Hadoop agent for this cluster","Failed to connect primary agent and unable to find standby Hadoop agent for this cluster"),
	NO_PRIMARY_AGENT_FOUND("5606","Unable to find the primary Hadoop agent for this cluster","Unable to find the primary Hadoop agent for this cluster"),
	ERROR_GETTING_HIVE_RESULTS("5596", "Unable to get hive results.Cannot connect to results Database", "Unable to get hive results.Cannot connect to results Database"),
	ERROR_GETTING_HIVE_TASK("5597", "Error in getting hive task info.", "Error in getting hive task info."),
	SAVE_HIVE_COLUMNS_ERROR("5595", "Error in saving the columns for the hive table", "Error in saving the columns for the hive table"),
	REFERENCE_DATA_REGEX_PATTERN_MISMATCH("5607","Reference data should match to regex pattern","Reference data should match to regex pattern"),
	PREDEFINED_REFERENCE_DATA_UNAVAILABLE("5608","No pre-defined reference list available for this expression","No pre-defined reference list available for this expression."),
	WARNING_EXPRESSION_NOT_MATCH_POLICY("5609","Warning: Some of the expression type are not the part of the policy and hence will be ignored. ","Warning: Some of the expression type are not the part of the policy and hence will be ignored. "),
	ERROR_SESSION_INTERCEPT("5610","Invalid Request or session intercepted.","Invalid Request or session intercepted."),
	VALIDATION_ERROR("5611","Validation Failed","Validation Failed."),
	WARNING_STRUCTURED_SERACH_FOR_UNSTRUCTURED("5612","Warning: Unstructured Discovery  will run although it has structure mapped to the directory. ","Warning: Unstructured Discovery  will run although it has structure mapped to the directory. "),
	ERROR_UPLOADING_SENSITIVE_DATA("5613","Error uploading sensitive data","Error uploading sensitive data"),
	FILE_FORMAT_MISMATCH("5614","File format mismatch","File format mismatch"),
	ERROR_DELETING_CUSTOM_TRANSFORMATION("5615","Custom transformation is in use","Remove custom transformation from task definition."),
	ERROR_SAVING_FLUME_FLOW("5616","Error saving flume flow","Error saving flume flow"),
	ERROR_LOADING_FLUME_FLOW("5617","Error loading flume flow","Error loading flume flow"),
	ERROR_DELETING_FLUME_FLOW("5618","Error deleting flume flow","Error loading flume flow"),
	ERROR_SAVING_FLUME_CONFIG_FILE("5619","Error saving flume Config File","Error saving flume Config File"),
	ERROR_SAVING_AGENT_METADATA("5620","Error saving Agent Metadata","Error saving Agent Metadata"),
	ERROR_LOADING_AGENT_INFO("5621","Agent not registered for the specified agent id","Agent not registered for the specified agent id"),
	TASK_ALREADY_RUNNING_ERROR("6061","An instance of this task is already running","An instance of this task is already running"),
	EMAIL_NOT_REGISTERED_FOR_USER("6062","Email is not registered for this user","Email not registered for this user"),
	ERROR_GETTING_USER_ROLE_INFO("6063","Error getting user role info","Error getting user role info"),
    ERROR_UPDATING_DEPENDENT_COLUMNS("5622", "Error Updating Dependent Columns", "Error occured while updating dependent columns"),
    LDAP_ERROR("5623", "Error occured while connecting to LDAP server", "Error occured while connecting to LDAP server"),
    PATH_IN_USE_ERROR("5624", "Can not update Network Path as it is in use.", "Can not update Network Path as it is in use."),
    ERROR_INVALID_FIELD_VALUE("5625","Invalid Field Value", "Invalid Field Value"),
    ERROR_UNSUPPORTED_FILE("5626", "Invalid configuration file type or format.", "Invalid configuration file type or format."),
    ERROR_GETTING_VERSION_DETAILS("5627", "Error while getting component version details", "Error message from GetComponentVersionDetailsServlet"),
    ERROR_GENERATING_UNIQUE_SESSIONID("5628", "Error while generating unique session id.", "Error while generating unique session id after limited retries."),
    ERROR_GETTING_LAST_LOGIN_TIME("5629", "Error while getting last login time.", "Error while getting last login time."),
	ERROR_GENERATING_UNIQUE_LINKKEY("5630", "Error while generating unique link key for notification.", "Error while generating unique link key after limited retries."),
	
	ERROR_RESUMING_TASKS("7001","Error while Resuming Tasks","Error while Resuming Tasks"),
	ERROR_UPDATING_TASK("7002","Error while Updating Task status.","Error while Updating Task status"),
	TEMPLATE_NOT_SELECTED("7003","Template is required for creating a flow","Template is required for creating a flow"),
	NO_ACTIVE_AGENT_AVAILABLE("7004","No active agent found, please make sure agent is active", "No active agent found, please make sure agent is active."),
	ERROR_VALIDATING_FLUME_CONFIG_FILE("7005","Error validating flume conf file,Source Path does not exist ","Error validating flume conf file,Source Path does not exist"),
	NO_FLUME_AGENT_FOR_CLUSTER("7006","No Flume Agent associated to this cluster","No flume agent associated to this cluster"),
	UNABLE_TO_CONNECT_CONTROLLER("7007","Unable to connnect controller","Unable to connnect controller"),
	ERROR_LOADING_FLUME_FLOW_METADATA("7008","Error loading metadata for this flow","Error loading metadata for this flow"),
	FLUME_PLUGIN_INACTIVE("7009","Plugin is inactive, so the flow is not started.Please start the plugin from the command line to start the flow.","Plugin is inactive, so the flow is not started.Please start the plugin from the command line to start the flow."),
	ERROR_VALIDATING_INTELLIMASK_REGEX("7010","The regex provided for Intellimask Masking Option is not valid.","The regex provided for Intellimask Masking Option is not valid."), 
	NO_CLUSTER_ACCESS("7011","User doesn't have access to any cluster","User doesn't have access to any cluster"),
	WARNING_CONSISTENT_MASKING_TASK("3032","Warning: Consistent Masking is not supported but since policy is with consistent flag, it will still be treated as non-consistent task","Warning: Consistent Masking is not supported but since policy is with consistent flag, it will still be treated as non-consistent task "),
	ERROR_INSTALLING_SSL_CERTIFICATE("7014","Error installing ssl certificate","Error installing ssl certificate"),
	ERROR_LICENSE_EXPIRED("", "Your Dataguise license has expired. Please contact your administrator to renew.", "Your Dataguise license has expired. Please contact your administrator to renew."),
	ERROR_FILE_SCAN_TIME_INVALID("7015", "File Modified Date Range is invalid.", "File Modified Date Range is invalid."),
	ERROR_TASK_FROM_FULL_TO_INCREMENT_FOR_DATE_RANGE("7016", "Cannot edit a date range task  to incremental scan type.", "Cannot edit a date range task  to incremental scan type."),
	ERROR_TIMERANGE_NOT_SUPPORTED("7017", "File Time Range functionality is not supported for any task type except Detection.", "File Time Range functionality is not supported for any task type except Detection."),
	ERROR_TIMERANGE_NOT_SPECIFIED_FOR_BOTH_END_AND_START("7018", "Both Time Range 'Files Modified After' and 'Files Modified Before' need to be provided.", "Both Time Range 'Files Modified After' and 'Files Modified Before' need to be provided."),
	ERROR_INCLUDING_EXCLUDE_PATH ("7020", "Following paths in excludeList are contradicting with inputpaths provided : ", "Following paths in excludeList are contradicting with inputpaths provided : "),
	SAVE_EXCLUDE_EXTENSION_ERROR ("7022", "Error saving HDFS task as some excluded extension are not in correct format.They should start with '.'", "Error saving HDFS task as some excluded extension are not in correct format.They should start with '.'"),
	CONSTRAIN_VOILATION_EXCLUSIONS("7022", "Error saving duplicate scan path for the excludeList.Please provide unqiue scan paths. ","Error saving duplicate scan path for the excludeList.Please provide unqiue scan paths. "),
	

	ERROR_GETTING_ATTRIBUTE_VALUE("7023", "Attribute not found in Manifest. ", "Attribute not found in Manifest. "),
	ERROR_EXECUTING_FOR_COMPOSITE_DEP_EXPRESSION("7024", "Unable to execute the task as expression/s or policy defined contain dependent or composite expression,valid for only HDFS auto discovery task. ", "Unable to execute the task as expression/s or policy defined contain dependent or composite expression,valid for only HDFS auto discovery task. "),
	ERROR_SENDING_HDFS_VERSION_DETAILS("7025", "Error sending HDFS agent version details. ", "Error sending HDFS agent version details. "),
	ERROR_SENDING_VERSION_DETAILS("7026", "Error sending version details. ", "Error sending version details. "),
	ERROR_SETTING_CUSTOM_VALIDATION_JAR("7027", "Error setting custom validation JARS in classpath. ", "Error setting custom validation JARS in classpath. "),
	ERROR_INITIALIZING_HDA("7028", "Error initializing Hadoop Data Agent. ", "Error initializing Hadoop Data Agent. "),
	ERROR_SENDING_CUSTOM_VALIDATION_MAP("7029", "Error while sending custom validation map to controller. ", "Error while sending custom validation map to controller. "),
	ERROR_SENDING_MONITORING_AGENT_VERSION_DETAILS("7031", "Error sending Monitoring Agent version details. ", "Error sending Monitoring Agent version details. "),
	ERROR_FETCHING_MONITORING_AGENT_URL("7032", "Internal Error while constructing Monitoring Agent URL from Metadata Repository", "Internal Error while constructing Monitoring Agent URL from Metadata Repository"),
	
	ERROR_DISCOVER_REGEX_INVALID_CHAR("7033", "Unable to save Expression because * is not allowed as Regular Expression.", "Unable to save Expression as * is not allowed as Regular Expression."),
	ERROR_DISCOVER_REGEX_INVALID_REGEX_DATA("7034", "Unable to validate Regex for Data.", "Unable to validate Regex for Data."),
	ERROR_DISCOVER_REGEX_INVALID_REGEX_COLUMNNAME("7035", "Unable to validate Regex for Column Name.", "Unable to validate Regex for Column Name."),
	
	ERROR_GETTING_REQUEST_RESPONSE("7036", "Error getting request or response", "Error getting request or response"),
	ERROR_READING_PROPERTY_FILE("7037", "Error reading property file", "Error reading property file"),
	ERROR_FETCHING_AGENT_DETAIL("7038", "Unable to get AgentDetails For StructureID.", "Unable to get AgentDetails For StructureID."),

	ERROR_COPYING_ACL_TO_CLUSTER("7042","Error copying acl.","Error copying acl."),
	ERROR_CREATING_DGM_POLICY("7043","Error creating DgMonitor policy","Error creating DgMonitor policy."),
	ERROR_DELETING_DGM_POLICY("7044","Error deleting DgMonitor policy","Error deleting DgMonitor policy."),
	ERROR_GETTING_DGM_POLICY("7045","Error getting DgMonitor policy","Error getting DgMonitor policy."),
	ERROR_INVALID_SITE_ID("7046","Invalid site or senstive data type Id","Invalid site or senstive data type Id"),
	ERROR_GETTING_DGM_ALERTS("7047","Error getting DgMonitor alerts","Error getting DgMonitor alerts."),
	ERROR_EXECUTING_HDFS_TASK_NO_STRUCTURE_ASSOCIATED("70462","'Structured' task cannot be EXECUTED because no structure is associated with the specified scan path(s)","'Structured' task cannot be EXECUTED because no structure is associated with the specified scan path(s)"),
	ERROR_SITE_ALREADY_EXISTS("7048","Site Alreay Exists","Site Alreay Exists"),
	ERROR_CONNECTING_EAGLE("7049","Error Connecting Eagle","Error Connecting Eagle"),
	COMPLIANCE_POLICY_OR_DESCRIPTION_IS_NULL("7050","Compliance policy or description is null","Compliance policy or description is null"),
	HIVE_TASK_NO_COLUMNS_ERROR ("7051", "No columns to scan for table name", "No columns to scan for table name"),
	HIVE_TASK_NO_TABLES_ERROR ("7052", "Error starting Hive task. No Tables/Columns to scan", "Error starting Hive task. No Tables/Columns to scan"),
	ERROR_DGM_POLICYNAME_ALREADY_EXISTS("7053","Alert Rule name already exists","Alert Rule name already exists."),
	ERROR_CREATING_EAGLE("7054","Error creating Eagle","Error creating Eagle."),
	ERROR_LOADING_EMR_CLUSTER_DETAIL("7055","Error loading EMR cluster details","Error loading EMR cluster details"),
	ERROR_SAVING_EMR_CLUSTER_DETAIL("7056","Error in saving EMR cluster details","Error in saving EMR cluster details"),
	NO_CLOUD_AGENT_CONFIGURED("7057","No Cloud agent has been configured","No Cloud agent has been configured"),
	ERROR_CREATING_EMR_CLUSTER("7058", "Error in creating cluster", "Error in creating cluster"),
	ERROR_DESTROY_EMR_CLUSTER("7059", "Error in destroying the cluster", "Error in destroying the cluster"),
	NO_S3_AGENT_FOUND("7060", "Error in connecting the S3 agent.", "Error in connecting the S3 agent."),
	DESTROY_CLUSTER_NOT_ALLOWED("7061", "Cannot destroy the cluster as task associated with it are still Runnning.", "Cannot destroy the cluster as task associated with it are still Runnning."),
	START_S3_TASK_ERROR ("7062", "Either the cluster is not provisioned , or no corresponding S3 agent is available.", "Either the cluster is not provisioned , or no corresponding S3 agent is available."),
	SAVE_S3_TASK_ERROR ("7063", "Error saving S3 task", "error message from Controller"),
	NO_CONFIGURATION_EXIST("7064","Cloud agent cannot provision cluster because no configuration details are available ","Cloud agent cannot provision cluster because no configuration details are available"),
	CLUSTER_ALREADY_PROVISIONED("7065","Error in provisioning the cluster as another cluster is already provisioned", "Error in provisioning the cluster as another cluster is already provisioned"),
	CANNOT_DESTROY_CLUSTER("7066", "Cannot destroy cluster as no response from cloud agent.", "Cannot destroy cluster as no response from cloud agent."),
	MULTIPLE_BUCKET_NOT_ALLOWED("7067", "Mutiple bucket scans in one task are not allowed.", "Mutiple bucket scans in one task are not allowed."),
	NO_CLUSTER_IN_RUNNING_MODE("7068", "No cluster in running mode to be destroyed.", "No cluster in running mode to be destroyed."),
	ERROR_GETTING_DOMAINS ("7069", "Unable to retrieve domains", "error message from Controller"),
	ERROR_INACTIVE_DOMAIN("7070","Unable to login.Please make sure that the domain is active.","Unable to login.Please make sure that the domain is active"),
	ERROR_DELETING_LDAP_DOMAIN("7071","One domain should be active.","One domain should be active."),
	LDAP_PARAMS_ERROR("7072","No ldap connection credentials found for the given cluster","No ldap connection connection credentials found for the given cluster"),
	NO_ATTIBUTE_FOUND("7073","No attribute of either 'ACL file','Ldap Page Size','Object Classes For User' found for the given cluster.","No attribute of either 'ACL file','Ldap Page Size','Object Classes For User' found for the given cluster."),
	NO_BASEDN_FOUND("7075","No base dn found for the cluster.","No base dn found for the cluster."),
	ERROR_DISCOVER_REGEX_BLANK_FILE("7076", "Unable to save Expression because blank file is not allowed in Reference Data List.", "Unable to save Expression as blank file is not allowed in Reference Data List."),
	ERROR_SETTING_REQUEST_PARAMS ("7077", "Error setting request params", "Error setting request params"),
	NOT_RESUMABLE_TASK("7078","Task is not resumable","Task is not resumable"),
	INVALID_MODULE("7079", "Invalid Module value.", "Invalid Module value."),
	ERROR_GETTING_CONDITION_TYPES("7080","Error in getting condition types", "Error in getting condition types"),
	ERROR_DELETING_SITES("7081","Error in deleting site", "Error in deleting site"),
	NOT_AUTO_DISCOVERY_TASK("7083", "Cancel functionality is not supported for any task type except Detection.", "Cancel functionality is not supported for any task type except Detection."),
	NOT_IN_RUNNING_STATE("7084", "Task is not in running state.", "Task is not in running state."),
	NOT_RDS_DATABASE("7085", "AWS RDS Database Connection in RDBMS Connection Manager and vice versa is not allowed", "AWS RDS Database Connection in RDBMS Connection Manager and vice versa is not allowed"),
//	IS_RDS_DATABASE("7086", "Connection is of RDS database", "Connection is not created.");

	HOST_NOT_ALLOWED_FOR_SOURCE_STREAM("7087", "Host is not allowed for the selected source stream.", "Host is not allowed for the selected source stream."),
	ERROR_DELETING_POLICY("7088", "Error deleting dgmonitor policy.", "Error deleting dgmonitor policy."),
	ERROR_DELETING_ALERT("7090", "Error deleting dgmonitor alert.", "Error deleting dgmonitor alert."),
	ERROR_OUTPUT_DIR_INFO_NOT_SPECIFIED("7091","Output dir for some scan paths is not specified.","Output dir for the some scan paths is not specified."),
	NOT_AZURE_DATABASE("7092", "AZURE Database Connection in RDBMS Connection Manager and vice versa is not allowed", "AZURE Database Connection in RDBMS Connection Manager and vice versa is not allowed"),
	REGEX_PATTERN_SYNTAX_ERROR("7093", "Wrong Regex Syntax","Wrong Regex Syntax");
	
	
	private final String errorCode;
	private final String errorMessage;
	private final String errorParams;

	ErrorConstants(String errorCode, String errorMessage, String errorParams){
		this.errorCode = errorCode;
		this.errorMessage = errorMessage;
		this.errorParams = errorParams;
	}

	public String errorCode() {
		return this.errorCode;
	}

	public String errorMessage() {
		return this.errorMessage;
	}

	public String errorParams() {
		return this.errorParams;
	}
}
